// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDy_HxUYVUtVcIVt9HnyyU15dUM8p1bV8M',
    appId: '1:112325490313:web:c4cbd43fe697999ff6b858',
    messagingSenderId: '112325490313',
    projectId: 'bookartify-idm',
    authDomain: 'bookartify-idm.firebaseapp.com',
    storageBucket: 'bookartify-idm.appspot.com',
    measurementId: 'G-R0M3L1PTSK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZs3jcWnjBcej1SqdstHrDlu5dCi-QNJo',
    appId: '1:112325490313:android:7ecb3ad5a2d16afdf6b858',
    messagingSenderId: '112325490313',
    projectId: 'bookartify-idm',
    storageBucket: 'bookartify-idm.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcz1FaoM3phJcgRHvZe3Ivf-O-E89tv9k',
    appId: '1:112325490313:ios:bf36723873d8e177f6b858',
    messagingSenderId: '112325490313',
    projectId: 'bookartify-idm',
    storageBucket: 'bookartify-idm.appspot.com',
    iosClientId: '112325490313-db290k78accek9hh8eejksiprkpkd7al.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookartify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcz1FaoM3phJcgRHvZe3Ivf-O-E89tv9k',
    appId: '1:112325490313:ios:bd8744252a34754ff6b858',
    messagingSenderId: '112325490313',
    projectId: 'bookartify-idm',
    storageBucket: 'bookartify-idm.appspot.com',
    iosClientId: '112325490313-a4bf5n1btr5vm5blp80tqql6c78e15t1.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookartify.RunnerTests',
  );
}
